sudo: required
language: generic
services:
  - docker
env:
  - TRAVIS_DEBIAN_DISTRIBUTION=jessie
script:
  - sh ci/travis.sh
branches:
  except:
  - "/^debian\/\d/"
deploy:
  file: ".bintray.json"
  key:
    secure: idHDCUXepsbZKEeMRTYSLs+brrr+++oxJwdBz/wt3hQHNw/ZYQ/1OLr/PhmI7YFKIF4ruluCUkpz2XgoTisNZ+d+sY3WMiWdf+3vMUu065V2Gn5+0I9XMkHgCI7HQ2SB0Zj6dinqUj5Pq6A1y3jO2FuXtVVbazzh5BCenyCFaItI2OEf2/KctYdc9lK5lLYwqd10Qqnb0Sm6jtgarkIzqSQOmTO1xDZBLfhyVRPUd86Xpxs/S7YaUonbXb2Xb5TyEAifpeNcio+5pftJq5OUsrjLjzbCBcKHSrHnTMgeqAC5FsGdL7v7l7hPVDULtx+zRUt2IzyBUi3zZaRzkGVxmhkkclu6Alkp+6ilrYwGllHxxbkXBUyWgI21zWPDX2zX1bLJegx+3w5HmW24GZXDr3vdlLbDTeMLf/9XRMLAZgf5S1OQZ4k7XpiTUQCL06sRCa40D3YTYW3+kkYdqUrkBHvCZid21bGZz8iugcCppLtT+nI3m2neGiHtrGWCeDN5+YqyTjWcyAT4P6kFQ3mdPqmKMNCREvTRwkyKX0d4KY//QGcPwXG/XPoAkW1/SKa3kd3RP5KsZ5CI+TU69ATi8M+JmUVdg1I6zZ2F7PhDPyE/waHeA9paQW/WH0bMApq5dINWv0hHoKWL/XrhG/d8f6rAr2Bl8iz4uEZF02zM4vM=
  provider: bintray
  user: marodru
